from .food import FoodBlueprint
from .category import CategoryBlueprint
from .group import GroupBlueprint
from .nutrient import NutrientBlueprint
from .nutrient_value import NutrientValueBlueprint
from .tribe import TribeBlueprint
from .origin import OriginBlueprint
from .local_food_name import LocalFoodNameBlueprint
from .editor import EditorBlueprint
from .index import IndexBlueprint
from .auth import AuthBlueprint