from .category import CategoryResource
from .food import FoodResource
from .group import GroupResource
from .nutrient import NutrientResource
from .nutrient_value import NutrientValueResource
from .local_food_name import LocalFoodNameResource
from .tribe import TribeResource
from .origin import OriginResource
from .editor import EditorResource
from .index import IndexResource
from .auth import AuthResource