"""feat: removed secret key

Revision ID: 68e34809a83e
Revises: bd8ba8f42a7b
Create Date: 2025-02-20 23:19:46.103002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e34809a83e'
down_revision = 'bd8ba8f42a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.drop_constraint('developers_secret_key_key', type_='unique')
        batch_op.drop_column('secret_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('developers_secret_key_key', ['secret_key'])

    # ### end Alembic commands ###
