"""fix: change jwt_id to public class

Revision ID: 876d8d279e99
Revises: 669b6d9f1274
Create Date: 2025-01-01 01:07:08.203391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d8d279e99'
down_revision = '669b6d9f1274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_id', sa.String(), nullable=True))
        batch_op.drop_column('_jwt_id')

    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_id', sa.String(), nullable=False))
        batch_op.drop_column('_jwt_id')

    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_id', sa.String(), nullable=True))
        batch_op.drop_column('_jwt_id')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_id', sa.String(), nullable=True))
        batch_op.drop_column('_jwt_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_jwt_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('jwt_id')

    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_jwt_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('jwt_id')

    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_jwt_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('jwt_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_jwt_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('jwt_id')

    # ### end Alembic commands ###
