"""feat: food domain models delete error

Revision ID: 97d1af6c82a8
Revises: 357ed89323e7
Create Date: 2024-12-19 00:17:16.064580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d1af6c82a8'
down_revision = '357ed89323e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('food_classes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_class', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('food_items_food_cless_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food_classes', ['food_class'], ['id'])
        batch_op.drop_column('food_cless')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_cless', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('food_items_food_cless_fkey', 'food_classes', ['food_cless'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('food_class')

    with op.batch_alter_table('food_classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
