"""feat: included food image

Revision ID: bd8ba8f42a7b
Revises: 876d8d279e99
Create Date: 2025-01-02 23:11:35.386466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8ba8f42a7b'
down_revision = '876d8d279e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
