"""fix: null constrain

Revision ID: f6e6d989c296
Revises: 97d1af6c82a8
Create Date: 2024-12-25 13:45:32.468528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e6d989c296'
down_revision = '97d1af6c82a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
